fos_user:
    db_driver: orm
    firewall_name: admin
    user_class: App\Domain\Model\User
    group:
        group_class:    App\Domain\Model\Group
    from_email:
        address:        app@localhost
        sender_name:    App