security:
    encoders:
        App\Domain\User\User:
            # php7.2
            algorithm: 'argon2i'
            # php7.0|7.1
            #algorithm: bcrypt
            #cost: 15

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN:       [ROLE_CLIENT, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider:               fos_userbundle
                csrf_token_generator:   security.csrf.token_manager
                login_path:             fos_user_security_login
                check_path:             fos_user_security_check
                default_target_path:    dashboard
                use_referer:            true
                remember_me:            true
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                secret: Oponiwolo477
                lifetime: 604800
            security: true
            anonymous: true
            switch_user: true
            logout_on_user_change: true

    access_control:
        # frontend login
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # anything else
        - { path: ^/, roles: [ROLE_USER] }