parameters:
    locale: de

framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/translations/'
            - '%kernel.project_dir%/bundles/Cwd/FosUserExtensionBundle/Resources/translations/'
        fallbacks:
            - '%locale%'
