version: '2'
services:
    app:
        image: busybox
        volumes:
            - /dev/shm:/dev/shm
            - .:/var/www/app
        tty: true
        user: "$USERID"
    mysql:
        image: mysql:5.7
        volumes:
            - .:/var/www/app
            - /var/lib/mysql
        environment:
            MYSQL_PASSWORD: dev
            MYSQL_USER: dev
            MYSQL_DATABASE: project
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
    php:
        image: dockerhub.cwd.at/docker/php/fpm-xdebug:7.1
        working_dir: /var/www/app
        user: "$USERID"
        volumes_from:
            - app

    apache:
        image: httpd:2.4
        volumes:
            - .docker/apache/apache2.conf:/usr/local/apache2/conf/httpd.conf:ro
            - .:/var/www/app
        ports:
            - 8400:80

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_USER: dev
            PMA_PASSWORD: dev
        ports:
            - 8401:80
