fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_login:
    path:  /login
    defaults: { _controller: "FOSUserBundle:Security:login" }
    methods: [GET, POST]

admin_login_check:
    path:  /login_check
    defaults: { _controller: "FOSUserBundle:Security:check" }
    methods: [GET, POST]


controllers:
    resource: ../src/Infrastructure/Web/Controller/
    type: annotation
    prefix:   /
