fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_login:
    path:  /login
    defaults: { _controller: "FOSUserBundle:Security:login" }
    methods: [GET, POST]

admin_login_check:
    path:  /login_check
    defaults: { _controller: "FOSUserBundle:Security:check" }
    methods: [GET, POST]


controllers:
    resource: ../src/Infrastructure/Web/Controller/
    type: annotation
    prefix:   /

avanzu_admin_profile:
    path: /profile/{userid}/
avanzu_admin_logout:
    path: /logout
avanzu_admin_all_tasks:
    path: /tasks/
avanzu_admin_show_task:
    path: /tasks/{taskid}/
avanzu_admin_all_notifications:
    path: /notifications/
avanzu_admin_show_notification:
    path: /notifications/{notifyid}/
avanzu_admin_all_messages:
    path: /messages/
avanzu_admin_show_message:
    path: /messages/{messageid}/