# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'de'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Domain/Model,Migrations,Repository,Tests}'


    App\Infrastructure\Web\Controller\:
        resource: '../src/Infrastructure/Web/Controller'
        tags: ['controller.service_arguments']

    # Manager Classes should always be public
    App\Domain\:
        resource: '../src/Domain/*/*Manager*'
        public: true

    App\Infrastructure\Web\EventListener\Menu\MainMenuListener:
        arguments:
            - "@security.authorization_checker"
            - "@translator.default"
        tags:
            - { name: kernel.event_listener, event: theme.sidebar_setup_menu, method: onSetupMenu, priority: 0 }
            - { name: kernel.event_listener, event: theme.breadcrumb, method: onSetupMenu, priority: 0 }

    App\Infrastructure\Web\EventListener\User\ShowUserListener:
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }
            - { name: kernel.event_listener, event: theme.sidebar_user, method: onShowuser }
